version: "3.9"
services:

  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres_data:/var/lib/pgsql/data

volumes:
  db-data: