version: "3.9"
services:

  postgres:
    restart: always
    image: postgres
    container_name: postgres_autoscrew
    environment:
      - POSTGRES_DB=autoscrew
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres_data:/var/lib/pgsql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  db-data: