version: '3'

services:
  mongo:
    image: bitnami/mongodb
    volumes: 
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: 123456
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: route_planner

volumes:
  mongodb_data:
    driver: local
