version: '3.9'

services:
  mongo:
    build: ./mongo
    volumes:
      - mongodb_data:/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: route_planner
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
